/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PACKAGEGUI;
import PACKAGEDB.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Asus
 */
public class ArsenalFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ArsenalFrame.class.getName());
    private String originalWeaponName = "";

    public ArsenalFrame() {
        initComponents();
        refreshTable();             
        setLocationRelativeTo(null); 

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        arsenalTbl = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        weaponNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        categoryCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        weightField = new javax.swing.JTextField();
        jLabelAttack = new javax.swing.JLabel();
        damageField = new javax.swing.JTextField();
        jLabelScaling = new javax.swing.JLabel();
        scalingField = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        damagetypeCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        arsenalTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        arsenalTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arsenalTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(arsenalTbl);

        addButton.setText("ADD");
        addButton.addActionListener(this::addButtonActionPerformed);

        updateButton.setText("UPDATE");
        updateButton.addActionListener(this::updateButtonActionPerformed);

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(this::deleteButtonActionPerformed);

        weaponNameField.addActionListener(this::weaponNameFieldActionPerformed);

        jLabel1.setText("Item Name:");

        jLabel2.setText("Item info");

        categoryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Weapon", "Talisman", "Consumable" }));
        categoryCombo.addActionListener(this::categoryComboActionPerformed);

        jLabel3.setText("Item Type:");

        jLabel4.setText("Weight:");

        weightField.addActionListener(this::weightFieldActionPerformed);

        jLabelAttack.setText("Damage:");

        damageField.addActionListener(this::damageFieldActionPerformed);

        jLabelScaling.setText("Scaling (e.g., Str B):");

        jTextField4.addActionListener(this::jTextField4ActionPerformed);

        jLabel7.setText("Search:");

        damagetypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "standard", "strike", "slash", "pierce", "N/A" }));
        damagetypeCombo.addActionListener(this::damagetypeComboActionPerformed);

        jLabel5.setText("Damage Type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(weaponNameField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelScaling)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(scalingField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(categoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(damagetypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(weightField)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelAttack)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(damageField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateButton)
                                    .addComponent(addButton)
                                    .addComponent(deleteButton)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(weaponNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(damagetypeCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(categoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(updateButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(weightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(damageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAttack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelScaling)
                    .addComponent(scalingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
     MainFrame main = new MainFrame();
    main.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void arsenalTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arsenalTblMouseClicked
int selectedRowIndex = arsenalTbl.getSelectedRow();
if (selectedRowIndex != -1) {
    DefaultTableModel model = (DefaultTableModel) arsenalTbl.getModel();
    
    originalWeaponName = model.getValueAt(selectedRowIndex, 1).toString();
    weaponNameField.setText(originalWeaponName);
    categoryCombo.setSelectedItem(model.getValueAt(selectedRowIndex, 2).toString());
    weightField.setText(model.getValueAt(selectedRowIndex, 3).toString());
    damageField.setText(model.getValueAt(selectedRowIndex, 4).toString());
    damagetypeCombo.setSelectedItem(model.getValueAt(selectedRowIndex, 5).toString()); // FIXED: lowercase 't'
    scalingField.setText(model.getValueAt(selectedRowIndex, 6).toString());
}
    }//GEN-LAST:event_arsenalTblMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
String category = categoryCombo.getSelectedItem().toString();
String sql = "UPDATE arsenal SET weapon_name = ?, category = ?, weight = ?, damage = ?, damage_type = ?, scaling = ? WHERE weapon_name = ?";

try (Connection conn = DBConnection.getConnection();
     PreparedStatement ps = conn.prepareStatement(sql)) {
    
    ps.setString(1, weaponNameField.getText().trim());
    ps.setString(2, category);
    ps.setDouble(3, Double.parseDouble(weightField.getText().trim()));
    ps.setInt(4, Integer.parseInt(damageField.getText().trim()));
    ps.setString(5, damagetypeCombo.getSelectedItem().toString()); // FIXED: lowercase 't'
    ps.setString(6, scalingField.getText().trim());
    ps.setString(7, originalWeaponName);

    if (ps.executeUpdate() > 0) {
        JOptionPane.showMessageDialog(this, category + " inventory updated.");
        refreshTable();
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error updating properties: " + e.getMessage());
}
    }//GEN-LAST:event_updateButtonActionPerformed

    private void weaponNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weaponNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weaponNameFieldActionPerformed

    private void weightFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightFieldActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void categoryComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboActionPerformed
    String selectedCategory = categoryCombo.getSelectedItem().toString();

    if (selectedCategory.equals("Weapon") || selectedCategory.equals("Shield")) {
        jLabelAttack.setText("Damage:"); 
        jLabelScaling.setText("Scaling (e.g., Str B):");
        damageField.setEnabled(true);         
        damagetypeCombo.setEnabled(true); // FIXED: lowercase 't'
    } else {
        jLabelAttack.setText("Damage: (N/A)");
        jLabelScaling.setText(selectedCategory.equals("Talisman") ? "Passive Effect:" : "Usage Effect:");
        damageField.setText("0");
        damageField.setEnabled(false);        
        damagetypeCombo.setSelectedItem("N/A"); // FIXED: lowercase 't'
        damagetypeCombo.setEnabled(false);      // FIXED: lowercase 't'
    }
    }//GEN-LAST:event_categoryComboActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
String name = weaponNameField.getText().trim();
String category = categoryCombo.getSelectedItem().toString();
String weightStr = weightField.getText().trim();
String attackStr = damageField.getText().trim();
String damageType = damagetypeCombo.getSelectedItem().toString(); // FIXED: lowercase 't'
String scaling = scalingField.getText().trim();

if (name.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Item name is required!", "Input Error", JOptionPane.WARNING_MESSAGE);
    return;
}

String sql = "INSERT INTO arsenal (weapon_name, category, weight, damage, damage_type, scaling) VALUES (?, ?, ?, ?, ?, ?)";

try (Connection conn = DBConnection.getConnection();
     PreparedStatement ps = conn.prepareStatement(sql)) {
    
    ps.setString(1, name);
    ps.setString(2, category);
    
    double weight = weightStr.isEmpty() ? 0.0 : Double.parseDouble(weightStr);
    int attack = attackStr.isEmpty() ? 0 : Integer.parseInt(attackStr);
    
    ps.setDouble(3, weight);
    ps.setInt(4, attack);
    ps.setString(5, damageType); 
    ps.setString(6, scaling);
    
    if (ps.executeUpdate() > 0) {
        JOptionPane.showMessageDialog(this, name + " added to your arsenal!");
        refreshTable();
    }
} catch (Exception ex) {
    JOptionPane.showMessageDialog(this, "Error saving entry: " + ex.getMessage());
}
    }//GEN-LAST:event_addButtonActionPerformed

    private void damageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_damageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_damageFieldActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
    // 1. Get the highlighted row index from the table
    int selectedRowIndex = arsenalTbl.getSelectedRow();
    
    // 2. Validation: Make sure they actually clicked a row first
    if (selectedRowIndex == -1) {
        JOptionPane.showMessageDialog(this, "Please select an item from the table grid to delete.", "Selection Missing", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // 3. Pull the Unique ID (Column 0) and Item Name (Column 1) directly from the row
    String itemId = arsenalTbl.getValueAt(selectedRowIndex, 0).toString();
    String itemName = arsenalTbl.getValueAt(selectedRowIndex, 1).toString();
    
    // 4. Prompt a safety confirmation window
    int verify = JOptionPane.showConfirmDialog(this, "Are you sure you want to permanently delete '" + itemName + "'?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
    if (verify != JOptionPane.YES_OPTION) {
        return; // Stop execution if they click 'No'
    }
    
    // 5. Execute the SQL target match using the Primary Key ID (safest approach)
    String sql = "DELETE FROM arsenal WHERE item_id = ?";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {
        
        ps.setInt(1, Integer.parseInt(itemId)); // Converts the string ID to a database integer
        
        int rowsDeleted = ps.executeUpdate();
        if (rowsDeleted > 0) {
            JOptionPane.showMessageDialog(this, itemName + " successfully purged from your inventory.");
            
            // 6. Instantly clear input UI boxes to keep things clean
            weaponNameField.setText("");
            weightField.setText("");
            damageField.setText("");
            scalingField.setText("");
            categoryCombo.setSelectedIndex(0);
            originalWeaponName = ""; // Reset tracker variable
            
            // 7. Refresh the UI table layout
            refreshTable();
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database Execution Failure: " + ex.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void damagetypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_damagetypeComboActionPerformed
  
    }//GEN-LAST:event_damagetypeComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ArsenalFrame().setVisible(true));
    }
   private void refreshTable() {
    DefaultTableModel model = (DefaultTableModel) arsenalTbl.getModel();
    model.setRowCount(0); 

    model.setColumnIdentifiers(new String[]{
        "ID", "Name", "Categ", "Weight", "Dmg", "Dmgtyp", "Mod/scale"
    });

    String sql = "SELECT * FROM arsenal";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {
        
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("item_id"),          
                rs.getString("weapon_name"),
                rs.getString("category"),
                rs.getDouble("weight"),
                rs.getInt("damage"), // Changed from attack_power to damage
                rs.getString("damage_type"), 
                rs.getString("scaling")
            });
        }
    } catch (SQLException ex) {
        System.err.println("Arsenal grid update stream dropped: " + ex.getMessage());
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTable arsenalTbl;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> categoryCombo;
    private javax.swing.JTextField damageField;
    private javax.swing.JComboBox<String> damagetypeCombo;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelAttack;
    private javax.swing.JLabel jLabelScaling;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField scalingField;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField weaponNameField;
    private javax.swing.JTextField weightField;
    // End of variables declaration//GEN-END:variables
}
