/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PACKAGEGUI;
import PACKAGEDB.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Asus
 */
public class BossFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BossFrame.class.getName());
    private String originalBossName = "";
    /**
     * Creates new form BuildFrame
     */
    public BossFrame() {
        initComponents();
        refreshTable();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        searchBarField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bossTbl = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        notesArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        physicalCombo = new javax.swing.JComboBox<>();
        elementalCombo = new javax.swing.JComboBox<>();
        statusCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addButton.setText("ADD");
        addButton.addActionListener(this::addButtonActionPerformed);

        updateButton.setText("UPDATE");
        updateButton.addActionListener(this::updateButtonActionPerformed);

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(this::deleteButtonActionPerformed);

        searchBarField.addActionListener(this::searchBarFieldActionPerformed);
        searchBarField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBarFieldKeyReleased(evt);
            }
        });

        bossTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Weakness", "Notes"
            }
        ));
        bossTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bossTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bossTbl);

        notesArea.setColumns(20);
        notesArea.setRows(5);
        jScrollPane2.setViewportView(notesArea);

        jLabel1.setText("notes:");

        jLabel2.setText("Search:");

        jLabel3.setText("Boss Info");

        jLabel4.setText("Name:");

        jLabel5.setText("Weakness:");

        nameField.addActionListener(this::nameFieldActionPerformed);

        physicalCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "standard", "strike", "slash", "pierce" }));

        elementalCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "magic", "fire", "lightning", "holy" }));

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bleed", "frostbite", "scarlet rot", "poison", "madness", "sleep", "death blight" }));

        jLabel6.setText("physical");

        jLabel7.setText("elemental");

        jLabel8.setText("status effect");

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(108, 108, 108)
                                                    .addComponent(jLabel7)
                                                    .addGap(44, 44, 44)
                                                    .addComponent(jLabel8))
                                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(12, 12, 12)
                                                    .addComponent(jLabel6))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(physicalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(elementalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(12, 12, 12)
                                                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(addButton, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBarField, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(physicalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(elementalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addButton)
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
  String name = nameField.getText().trim();
    String notes = notesArea.getText().trim();

    if (name.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Boss Name can't be empty!", "Input Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    java.util.List<String> weaknesses = new java.util.ArrayList<>();
    String phys = physicalCombo.getSelectedItem().toString();
    String elem = elementalCombo.getSelectedItem().toString();
    String status = statusCombo.getSelectedItem().toString();

    if (!phys.equals("None") && !phys.contains("Item")) weaknesses.add(phys);
    if (!elem.equals("None") && !elem.contains("Item")) weaknesses.add(elem);
    if (!status.equals("None") && !status.contains("Item")) weaknesses.add(status);

    String combinedWeakness = String.join(", ", weaknesses);
    String sql = "INSERT INTO bosses (name, weakness, notes) VALUES (?, ?, ?)";
    
    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {
        
        ps.setString(1, name);
        ps.setString(2, combinedWeakness);
        ps.setString(3, notes);
        
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Boss configuration added successfully!");
        
        refreshTable(); // <-- MOVED HERE: Refreshes the grid upon successful entry!
        
        // Clear all fields for the next input
        nameField.setText("");
        notesArea.setText("");
        physicalCombo.setSelectedIndex(0);
        elementalCombo.setSelectedIndex(0);
        statusCombo.setSelectedIndex(0);
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database write failure: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        // Clear name field for retry
        nameField.setText("");
    }
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
    String name = nameField.getText().trim();
    String notes = notesArea.getText().trim();

    if (name.isEmpty() || originalBossName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select a boss from the table first before updating.", "Selection Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Capture the latest weakness combinations from the dropdown boxes
    java.util.List<String> weaknesses = new java.util.ArrayList<>();
    String phys = physicalCombo.getSelectedItem().toString();
    String elem = elementalCombo.getSelectedItem().toString();
    String status = statusCombo.getSelectedItem().toString();

    if (!phys.equals("None") && !phys.contains("Item")) weaknesses.add(phys);
    if (!elem.equals("None") && !elem.contains("Item")) weaknesses.add(elem);
    if (!status.equals("None") && !status.contains("Item")) weaknesses.add(status);
    String combinedWeakness = String.join(", ", weaknesses);

    // SQL query mapping to match your structural layout
    String sql = "UPDATE bosses SET name = ?, weakness = ?, notes = ? WHERE name = ?";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {
        
        ps.setString(1, name);
        ps.setString(2, combinedWeakness);
        ps.setString(3, notes);
        ps.setString(4, originalBossName); // Find the original record row
        
        int modifiedRows = ps.executeUpdate();
        if (modifiedRows > 0) {
            JOptionPane.showMessageDialog(this, "Boss strategy parameters updated successfully!");
            refreshTable(); // Refresh user view grid
        } else {
            JOptionPane.showMessageDialog(this, "No boss record found matching: " + originalBossName, "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database update failure: " + ex.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
   String name = nameField.getText().trim();

    if (name.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter a boss name to delete.", "Input Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int choice = JOptionPane.showConfirmDialog(this, "Permanently delete " + name + " from active listings?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
    if (choice != JOptionPane.YES_OPTION) {
        return;
    }

    String sql = "DELETE FROM bosses WHERE name = ?";
    
    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {
        
        ps.setString(1, name);
        int rowsDeleted = ps.executeUpdate();
        
        if (rowsDeleted > 0) {
            JOptionPane.showMessageDialog(this, "Boss entry erased successfully.");
            refreshTable();
            // Clear out interface components cleanly
            nameField.setText("");
            notesArea.setText("");
            physicalCombo.setSelectedIndex(0);
            elementalCombo.setSelectedIndex(0);
            statusCombo.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(this, "No boss found matching that name entry.", "Not Found", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "SQL execution error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void searchBarFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarFieldActionPerformed

    private void searchBarFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarFieldKeyReleased
String targetInput = searchBarField.getText().trim();
    if (targetInput.isEmpty()) {
        refreshTable();
        return;
    }
    DefaultTableModel gridDataView = (DefaultTableModel) bossTbl.getModel();
    gridDataView.setRowCount(0); 

    // Explicitly title columns to match your text notes change
    gridDataView.setColumnIdentifiers(new String[]{"ID", "Boss Name", "Weaknesses", "Notes"});

    String sql = "SELECT boss_id, name, recommended_damage_type, notes FROM bosses WHERE name LIKE ?";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {
        
        ps.setString(1, "%" + targetInput + "%");
        ResultSet set = ps.executeQuery();
        
        while (set.next()) {
            gridDataView.addRow(new Object[]{
                set.getInt("boss_id"),
                set.getString("name"),
                set.getString("weakness"),
                set.getString("notes")
            });
        }
    } catch (SQLException ex) {
        System.err.println("Live lookup interface stream failure context: " + ex.getMessage());
    }  
    }//GEN-LAST:event_searchBarFieldKeyReleased

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
    MainFrame main = new MainFrame();
    main.setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void bossTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bossTblMouseClicked
    int selectedRowIndex = bossTbl.getSelectedRow();
if (selectedRowIndex != -1) {
    DefaultTableModel model = (DefaultTableModel) bossTbl.getModel();
    
    // Save the old name from Column 1
    originalBossName = model.getValueAt(selectedRowIndex, 1).toString();
    
    // Fill the Name text field and Notes area automatically
    nameField.setText(originalBossName);
    notesArea.setText(model.getValueAt(selectedRowIndex, 3).toString());
}
    }//GEN-LAST:event_bossTblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BossFrame().setVisible(true));
    }
    private void refreshTable() {
    DefaultTableModel gridDataView = (DefaultTableModel) bossTbl.getModel();
    gridDataView.setRowCount(0); // Clear outdated rows

    gridDataView.setColumnIdentifiers(new String[]{"ID", "Boss Name", "Weaknesses", "Notes"});

    // Fixed query: Select the actual 'weakness' column to match your getString call below
    String sql = "SELECT boss_id, name, weakness, notes FROM bosses";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql);
         ResultSet set = ps.executeQuery()) {
        
        while (set.next()) {
            gridDataView.addRow(new Object[]{
                set.getInt("boss_id"),
                set.getString("name"),
                set.getString("weakness"), // Safe now!
                set.getString("notes")
            });
        }
    } catch (SQLException ex) {
        System.err.println("Automatic refresh failure context: " + ex.getMessage());
        JOptionPane.showMessageDialog(this, "Failed to load table content: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTable bossTbl;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox<String> elementalCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextArea notesArea;
    private javax.swing.JComboBox<String> physicalCombo;
    private javax.swing.JTextField searchBarField;
    private javax.swing.JComboBox<String> statusCombo;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
