/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PACKAGEGUI;
import PACKAGEDB.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Asus
 */
public class CharacterFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CharacterFrame.class.getName());
    private String originalName = "";
    /**
     * Creates new form CharacterFrame
     */
    public CharacterFrame() {
    initComponents();
    refreshTable();              // Automatically load existing stats
    setLocationRelativeTo(null); // Centers window on screen

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        levelField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        vigorField = new javax.swing.JTextField();
        enduranceField = new javax.swing.JTextField();
        mindField = new javax.swing.JTextField();
        strengthField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dexterityField = new javax.swing.JTextField();
        intelligenceField = new javax.swing.JTextField();
        faithField = new javax.swing.JTextField();
        arcaneField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        searchBarField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCharacters = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        buildCombo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        jLabel1.setText("Character info");

        jLabel2.setText("Name:");

        jLabel3.setText("Level:");

        nameField.addActionListener(this::nameFieldActionPerformed);

        jLabel4.setText("Stat Allocated Levels");

        jLabel5.setText("Vigor:");

        jLabel6.setText("Mind:");

        jLabel7.setText("Endurance:");

        jLabel8.setText("Strength");

        vigorField.addActionListener(this::vigorFieldActionPerformed);

        mindField.addActionListener(this::mindFieldActionPerformed);

        jLabel9.setText("Dexterity:");

        jLabel10.setText("Intelligence:");

        jLabel11.setText("Faith:");

        jLabel12.setText("Arcane:");

        addButton.setText("ADD");
        addButton.addActionListener(this::addButtonActionPerformed);

        updateButton.setText("UPDATE");
        updateButton.addActionListener(this::updateButtonActionPerformed);

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(this::deleteButtonActionPerformed);

        searchBarField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBarFieldKeyReleased(evt);
            }
        });

        tblCharacters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCharacters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCharactersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCharacters);

        jLabel13.setText("Search:");

        buildCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SRT", "DEX", "INT", "FAI", "ARC", "Quality" }));

        jLabel14.setText("Build:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(backButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBarField))
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(89, 89, 89))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buildCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel5))
                                            .addComponent(jLabel7)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(12, 12, 12)
                                        .addComponent(levelField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mindField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(strengthField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(enduranceField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(vigorField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(faithField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(intelligenceField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(arcaneField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dexterityField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addButton)
                            .addComponent(deleteButton)
                            .addComponent(updateButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(vigorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(dexterityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(levelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(mindField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(intelligenceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(enduranceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faithField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton)
                    .addComponent(buildCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(strengthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(arcaneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
    MainFrame main = new MainFrame();
    main.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void vigorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vigorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vigorFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
// 1. USE THE UTILITY MODULE (Requirement 4.2: Validate user input)
    if (!PACKAGEUTIL.ValidationUtils.isNotEmpty(nameField.getText(), "Character Name")) return;
    if (!PACKAGEUTIL.ValidationUtils.isValidInteger(levelField.getText(), "Level")) return;
    if (!PACKAGEUTIL.ValidationUtils.isValidInteger(vigorField.getText(), "Vigor")) return;

    // 2. USE THE OOP MODEL LAYER (Requirement 6.2: Object interaction)
    PACKAGEMODEL.Character newChar = new PACKAGEMODEL.Character(
        nameField.getText(),
        Integer.parseInt(levelField.getText().trim()),
        buildCombo.getSelectedItem().toString(),
        Integer.parseInt(vigorField.getText().trim()),
        Integer.parseInt(mindField.getText().trim())
    );

    // 3. PASS THE OBJECT TO DATABASE (Clean CRUD separation)
    String sql = "INSERT INTO characters (name, level, build_type, vigor, mind) VALUES (?, ?, ?, ?, ?)";
    try (Connection conn = PACKAGEDB.DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {
        
        ps.setString(1, newChar.getName()); // Reading from the object, not the text field!
        ps.setInt(2, newChar.getLevel());
        ps.setString(3, newChar.getBuildType());
        ps.setInt(4, newChar.getVigor());
        ps.setInt(5, newChar.getMind());
        
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Character Oath Inscribed!");
        refreshTable();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
    }
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
   String name = nameField.getText().trim();
String buildSelected = buildCombo.getSelectedItem().toString();

if (name.isEmpty() || originalName.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please select a character profile from the table first.", "Input Error", JOptionPane.WARNING_MESSAGE);
    return;
}

// SQL query using 12 parameters (name is updated, searched by originalName)
String sql = "UPDATE characters SET name = ?, build_type = ?, level = ?, vigor = ?, mind = ?, "
           + "endurance = ?, strength = ?, dexterity = ?, intelligence = ?, faith = ?, arcane = ? "
           + "WHERE name = ?";

try (Connection conn = DBConnection.getConnection();
     PreparedStatement ps = conn.prepareStatement(sql)) {
    
    ps.setString(1, name); 
    ps.setString(2, buildSelected);
    ps.setInt(3, Integer.parseInt(levelField.getText().trim()));
    ps.setInt(4, Integer.parseInt(vigorField.getText().trim()));
    ps.setInt(5, Integer.parseInt(mindField.getText().trim()));
    ps.setInt(6, Integer.parseInt(enduranceField.getText().trim()));
    ps.setInt(7, Integer.parseInt(strengthField.getText().trim()));
    ps.setInt(8, Integer.parseInt(dexterityField.getText().trim()));
    ps.setInt(9, Integer.parseInt(intelligenceField.getText().trim()));
    ps.setInt(10, Integer.parseInt(faithField.getText().trim()));
    ps.setInt(11, Integer.parseInt(arcaneField.getText().trim()));
    
    ps.setString(12, originalName); // Safe unique look-up string

    int modifiedRows = ps.executeUpdate();
    if (modifiedRows > 0) {
        JOptionPane.showMessageDialog(this, "Character parameters shifted successfully.");
        originalName = name; // Update tracking context to match new identity
        refreshTable();
    } else {
        JOptionPane.showMessageDialog(this, "Profile not found.", "Error", JOptionPane.ERROR_MESSAGE);
    }
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "Ensure stats use numbers only.", "Format Error", JOptionPane.ERROR_MESSAGE);
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Database failure: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
    // Inside your DELETE action listener:
String name = nameField.getText().trim();

if (name.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Enter name text context to drop profile listing.", "Input Error", JOptionPane.WARNING_MESSAGE);
    return;
}

int verificationPrompt = JOptionPane.showConfirmDialog(this, "Permanently delete entry '" + name + "'?", "Confirm Erase", JOptionPane.YES_NO_OPTION);
if (verificationPrompt != JOptionPane.YES_OPTION) return;

String sql = "DELETE FROM characters WHERE name = ?";

try (Connection conn = DBConnection.getConnection();
     PreparedStatement ps = conn.prepareStatement(sql)) {
    
    ps.setString(1, name);
    int rowsDeleted = ps.executeUpdate();
    
    if (rowsDeleted > 0) {
        JOptionPane.showMessageDialog(this, "Character build completely removed.");
        refreshTable();
        
        nameField.setText(""); levelField.setText(""); buildCombo.setSelectedIndex(0);
        vigorField.setText(""); mindField.setText(""); enduranceField.setText("");
        strengthField.setText(""); dexterityField.setText(""); intelligenceField.setText("");
        faithField.setText(""); arcaneField.setText("");
    } else {
        JOptionPane.showMessageDialog(this, "Could not find profile.", "Not Found", JOptionPane.INFORMATION_MESSAGE);
    }
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "SQL error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void searchBarFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarFieldKeyReleased
   String targetInput = searchBarField.getText().trim();

    if (targetInput.isEmpty()) {
        refreshTable();
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tblCharacters.getModel();
    model.setRowCount(0);
    
    // Explicitly set the column headers here too so columns match layout rules
    model.setColumnIdentifiers(new String[]{
        "ID", "Name", "Build Type", "Level", "Vig", "Min", "End", "Str", "Dex", "Int", "Fai", "Arc"
    });

    String sql = "SELECT * FROM characters WHERE name LIKE ?";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {
        
        ps.setString(1, "%" + targetInput + "%");
        ResultSet rs = ps.executeQuery();
        
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("char_id"), rs.getString("name"), rs.getString("build_type"),
                rs.getInt("level"), rs.getInt("vigor"), rs.getInt("mind"),
                rs.getInt("endurance"), rs.getInt("strength"), rs.getInt("dexterity"),
                rs.getInt("intelligence"), rs.getInt("faith"), rs.getInt("arcane")
            });
        }
    } catch (SQLException ex) {
        System.err.println("Search exception: " + ex.getMessage());
    }
    }//GEN-LAST:event_searchBarFieldKeyReleased

    private void mindFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mindFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mindFieldActionPerformed

    private void tblCharactersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCharactersMouseClicked
    int selectedRowIndex = tblCharacters.getSelectedRow();
if (selectedRowIndex != -1) {
    DefaultTableModel model = (DefaultTableModel) tblCharacters.getModel();
    
    // 1. Store the database name in our tracking variable (Column 1)
    originalName = model.getValueAt(selectedRowIndex, 1).toString();
    
    // 2. Automatically populate all fields on your screen
    nameField.setText(model.getValueAt(selectedRowIndex, 1).toString());
    buildCombo.setSelectedItem(model.getValueAt(selectedRowIndex, 2).toString());
    levelField.setText(model.getValueAt(selectedRowIndex, 3).toString());
    vigorField.setText(model.getValueAt(selectedRowIndex, 4).toString());
    mindField.setText(model.getValueAt(selectedRowIndex, 5).toString());
    enduranceField.setText(model.getValueAt(selectedRowIndex, 6).toString());
    strengthField.setText(model.getValueAt(selectedRowIndex, 7).toString());
    dexterityField.setText(model.getValueAt(selectedRowIndex, 8).toString());
    intelligenceField.setText(model.getValueAt(selectedRowIndex, 9).toString());
    faithField.setText(model.getValueAt(selectedRowIndex, 10).toString());
    arcaneField.setText(model.getValueAt(selectedRowIndex, 11).toString());
}
    }//GEN-LAST:event_tblCharactersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CharacterFrame().setVisible(true));
    }
private void refreshTable() {
// Target jTable2 instead of jTable1
    DefaultTableModel model = (DefaultTableModel) tblCharacters.getModel();
    model.setRowCount(0); 

    // Include "Min" in headers
    model.setColumnIdentifiers(new String[]{
        "ID", "Name", "Build Type", "Level", "Vig", "Min", "End", "Str", "Dex", "Int", "Fai", "Arc"
    });

    String sql = "SELECT * FROM characters";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {
        
        while (rs.next()) {
            // Include rs.getInt("mind") in its correct slot
            model.addRow(new Object[]{
                rs.getInt("char_id"),
                rs.getString("name"),
                rs.getString("build_type"),
                rs.getInt("level"),
                rs.getInt("vigor"),
                rs.getInt("mind"), // Added here
                rs.getInt("endurance"),
                rs.getInt("strength"),
                rs.getInt("dexterity"),
                rs.getInt("intelligence"),
                rs.getInt("faith"),
                rs.getInt("arcane")
            });
        }
    } catch (SQLException ex) {
        System.err.println("Character table refresh failure: " + ex.getMessage());
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField arcaneField;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> buildCombo;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField dexterityField;
    private javax.swing.JTextField enduranceField;
    private javax.swing.JTextField faithField;
    private javax.swing.JTextField intelligenceField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField levelField;
    private javax.swing.JTextField mindField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField searchBarField;
    private javax.swing.JTextField strengthField;
    private javax.swing.JTable tblCharacters;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField vigorField;
    // End of variables declaration//GEN-END:variables
}
