/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PACKAGEGUI;
import PACKAGEDB.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Asus
 */
public class RoundtableFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RoundtableFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public RoundtableFrame() {
        initComponents();
        setLocationRelativeTo(null); 
    populateCharacterCombo();    
    populateBossCombo();
    }
private void populateCharacterCombo() {
    characterCombo.removeAllItems();
    String sql = "SELECT name FROM characters";
    
    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {
         
        while (rs.next()) {
            characterCombo.addItem(rs.getString("name"));
        }
    } catch (SQLException ex) {
        System.err.println("Failed to load characters into Roundtable: " + ex.getMessage());
    }
}

private void populateBossCombo() {
    bossCombo.removeAllItems();
    String sql = "SELECT name FROM bosses";
    
    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {
         
        while (rs.next()) {
            bossCombo.addItem(rs.getString("name"));
        }
    } catch (SQLException ex) {
        System.err.println("Failed to load bosses into Roundtable: " + ex.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        characterCombo = new javax.swing.JComboBox<>();
        bossCombo = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayArea = new javax.swing.JTextArea();
        logVictoryButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Back");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel1.setText("Battle Prep");

        jLabel2.setText("Character");

        jLabel3.setText("Boss");

        characterCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bossCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("Seek Guidance");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel4.setText("Build Recommendation");

        displayArea.setColumns(20);
        displayArea.setRows(5);
        jScrollPane1.setViewportView(displayArea);

        logVictoryButton.setText("Inscribe Remembrance");
        logVictoryButton.addActionListener(this::logVictoryButtonActionPerformed);

        jLabel5.setText("Transaction logs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(characterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(bossCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel3)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton2)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(logVictoryButton)
                                            .addComponent(jLabel5))
                                        .addGap(15, 15, 15))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(characterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bossCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(logVictoryButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    MainFrame main = new MainFrame();
    main.setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// Step 1: Safely grab selected text from combo boxes
    if (characterCombo.getSelectedItem() == null || bossCombo.getSelectedItem() == null) {
        displayArea.setText("Please select both a Character and a Boss first.");
        return;
    }
    
    String selectedChar = characterCombo.getSelectedItem().toString();
    String selectedBoss = bossCombo.getSelectedItem().toString();

    // Step 2: Use an explicit INNER JOIN to link characters and bosses safely without column conflicts
    String basicSql = "SELECT c.strength, c.dexterity, c.intelligence, c.faith, c.arcane, "
                   + "b.weakness, b.notes "
                   + "FROM characters c "
                   + "CROSS JOIN bosses b "
                   + "WHERE c.name = ? AND b.name = ?";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(basicSql)) {
        
        ps.setString(1, selectedChar);
        ps.setString(2, selectedBoss);
        
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                // Safely handle null weaknesses
                String bossWeakness = rs.getString("weakness");
                if (bossWeakness == null) {
                    bossWeakness = "";
                }
                String notes = rs.getString("notes");
                if (notes == null) {
                    notes = "";
                }

                // Extract Character stats
                int str = rs.getInt("strength");
                int dex = rs.getInt("dexterity");
                int intel = rs.getInt("intelligence");
                int fai = rs.getInt("faith");
                int arc = rs.getInt("arcane");

                // Determine your character's highest primary attribute
                String primaryStat = "Str";
                int maxVal = str;
                if (dex > maxVal) { primaryStat = "Dex"; maxVal = dex; }
                if (intel > maxVal) { primaryStat = "Int"; maxVal = intel; }
                if (fai > maxVal) { primaryStat = "Fai"; maxVal = fai; }
                if (arc > maxVal) { primaryStat = "Arc"; maxVal = arc; }

                StringBuilder weaponsList = new StringBuilder();
                StringBuilder talismanList = new StringBuilder();
                
                String bestWeapon = "None found in custom Arsenal matching weaknesses.";
                int highestDamage = -1;

                // Step 3: Query Arsenal. We fetch all columns safely to avoid sub-query context errors.
                String arsenalSql = "SELECT weapon_name, category, damage, damage_type, scaling FROM arsenal";
                
                try (PreparedStatement psWep = conn.prepareStatement(arsenalSql);
                     ResultSet rsWep = psWep.executeQuery()) {
                    
                    while (rsWep.next()) {
                        String wepName = rsWep.getString("weapon_name");
                        String category = rsWep.getString("category");
                        int dmg = rsWep.getInt("damage");
                        String wepType = rsWep.getString("damage_type");
                        String wepScaling = rsWep.getString("scaling");

                        if (category == null) category = "";
                        if (wepType == null) wepType = "";
                        if (wepScaling == null) wepScaling = "";

                        // Check if the arsenal item matches any of the boss's listed weaknesses
                        boolean matchesWeakness = false;
                        for (String weakness : bossWeakness.split(",")) {
                            String trimmedWeakness = weakness.trim();
                            if (!trimmedWeakness.isEmpty() && wepType.equalsIgnoreCase(trimmedWeakness)) {
                                matchesWeakness = true;
                                break;
                            }
                        }

                        // Process Weapons
                        if (category.equalsIgnoreCase("Weapon") && matchesWeakness) {
                            weaponsList.append("- ").append(wepName)
                                       .append(" (Damage: ").append(dmg)
                                       .append(", Type: ").append(wepType)
                                       .append(", Scaling: ").append(wepScaling).append(")\n");
                            
                            // Judge if this is the absolute best choice for your stats
                            if (wepScaling.toLowerCase().contains(primaryStat.toLowerCase())) {
                                if (dmg > highestDamage) {
                                    highestDamage = dmg;
                                    bestWeapon = wepName + " [Base Damage: " + dmg + " | Damage Type: " + wepType + "]";
                                }
                            }
                        }
                        
                        // Process Talismans
                        if (category.equalsIgnoreCase("Talisman")) {
                            boolean relevantTalisman = false;
                            for (String weakness : bossWeakness.split(",")) {
                                String trimmedWeakness = weakness.trim();
                                if (!trimmedWeakness.isEmpty() && (wepScaling.toLowerCase().contains(trimmedWeakness.toLowerCase()) || 
                                    wepScaling.toLowerCase().contains(primaryStat.toLowerCase()))) {
                                    relevantTalisman = true;
                                    break;
                                }
                            }

                            if (relevantTalisman) {
                                talismanList.append("- ").append(wepName).append(" (Passive: ").append(wepScaling).append(")\n");
                            }
                        }
                    }
                }
                
                // Fallbacks if lists are empty
                if (weaponsList.length() == 0) {
                    weaponsList.append("No items in your Arsenal match the boss's element/damage weaknesses.\n");
                }
                if (talismanList.length() == 0) {
                    talismanList.append("No synergistic talismans found for this scaling or element focus.\n");
                }

                // Step 4: Print findings cleanly onto the displayArea
                displayArea.setText(
                    "=================== ROUNDTABLE HOLD TACTICAL REPORT ===================\n\n" +
                    "👤 BUILD FOCUS:\n" + "Your primary attribute is [" + primaryStat + "] with a score of " + maxVal + ".\n\n" +
                    "🎯 TARGET VULNERABILITIES:\n" + "The boss is vulnerable to: [" + bossWeakness + "]\n\n" +
                    "👑 RECOMMENDED PRIMARY WEAPON:\n" + bestWeapon + "\n\n" +
                    "⚔️ ALL COMPATIBLE WEAPONS AVAILABLE:\n" + weaponsList.toString() + "\n" +
                    "💍 RECOMMENDED TALISMAN SYNERGIES:\n" + talismanList.toString() + "\n" +
                    "📝 STRATEGY & NOTES:\n" + notes
                );
            } else {
                displayArea.setText("Error: Could not locate data for selected Character or Boss.");
            }
        }
    } catch (SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Database Engine Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void logVictoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logVictoryButtonActionPerformed
    // 1. Grab selected items from your GUI dropdowns
    String selectedChar = characterCombo.getSelectedItem().toString();
    String selectedBoss = bossCombo.getSelectedItem().toString();
    
    // 2. Prepare the transactional SQL statement
    String sql = "INSERT INTO boss_conquests (character_name, boss_name) VALUES (?, ?)";
    
    try (Connection conn = PACKAGEDB.DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {
         
        ps.setString(1, selectedChar);
        ps.setString(2, selectedBoss);
        
        // Execute transaction write
        ps.executeUpdate();
        
        // 3. Output to your JTextArea right on the screen!
        displayArea.append("⚡ LORE UPDATE: [" + selectedChar + "] has challenged and FELLED [" + selectedBoss + "]!\n");
        
        JOptionPane.showMessageDialog(this, "Remembrance Inscribed into the Roundtable Hold!", "Victory Logged", JOptionPane.INFORMATION_MESSAGE);
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Transaction dropped: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_logVictoryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RoundtableFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bossCombo;
    private javax.swing.JComboBox<String> characterCombo;
    private javax.swing.JTextArea displayArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logVictoryButton;
    // End of variables declaration//GEN-END:variables
}
